### ISSUE TITLE
Last modified bar not showing

### ISSUE THREAD

**Issue by jdlrobson** [joakin/loot-ui#29]
Legally this has to be shown so we should make sure to include this in the demo/proof of concept.

Expected: last modified bar at bottom with working links to history page.

**Comment by jdlrobson** [comment]
To fully render it this depends on #41 follow up patch on way..

**Comment by joakin** [comment]
I've reviewed and left a bunch of comments.

Also commented on the approach with some thoughts: https://github.com/joakin/loot-ui/pull/32#issuecomment-164424914 and https://github.com/joakin/loot-ui/pull/32#issuecomment-164425692 since it seems like that info is already on the document so we can return it from the `/slim` endpoints directly extracted from the restbase html.

Should we chat over there?
